/* eslint-disable camelcase */
// Generated by https://quicktype.io

export interface ManifestFolderList {
  name: string;
  path: string;
  sha: string;
  size: number;
  url: string;
  html_url: string;
  git_url: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  download_url?: any;
  type: string;
  _links: Links;
}

interface Links {
  self: string;
  git: string;
  html: string;
}
